name: Build and Push Docker Image

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Prepare Docker Metadata
        id: meta
        run: |
          # リポジトリ名を小文字に変換
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          # ブランチ名を小文字に変換
          BRANCH_LOWER=$(echo "${GITHUB_REF#refs/heads/}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9.]/-/g')
          
          echo "repo=${REPO_LOWER}" >> $GITHUB_OUTPUT
          echo "branch=${BRANCH_LOWER}" >> $GITHUB_OUTPUT
        

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.repo }}/app:${{ steps.meta.outputs.branch }}
            ${{ github.ref == 'refs/heads/main' && format('ghcr.io/{0}/app:latest', steps.meta.outputs.repo) || '' }}
  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      # Runner(LXC)に最新のソースコードをチェックアウト
      - uses: actions/checkout@v4

      # マイグレーションに必要な依存関係をインストール
      - name: Install dependencies
        run: npm install

      # アプリの更新（イメージのプルと再起動）
      - name: Pull new image and restart
        run: |
          # アプリ実行ディレクトリへ移動
          mkdir -p /home/graphly/graphly-task
          cd /home/graphly/graphly-task
          # Git上の最新のdocker-compose.prod.ymlを配置
          cp $GITHUB_WORKSPACE/docker-compose.prod.yml .
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d

      # データベースの自動マイグレーション
      - name: Run Database Migration
        run: |
          DATABASE_URL=${{ secrets.DATABASE_URL_LOCAL }} npx drizzle-kit push
